#
# Playbook should be run as follows:
# 
# 1. Login as 'ansible' user
# 2. Run the following to use vagrant's key first to install ansible's key
#
#     ansible-playbook -vvvv --extra-var hosts=pizservers -i ./inventory --user pi -K pi_prov_playbook.yml --ask-pass
#
#        - Just change the following in the above command:
#              - Path to private_key (/machines/app, etc..)
#              - host value per the inventory file
#      
#!/usr/bin/env ansible-playbook
---
- name: "Provisioning playbook for Inventory groups other than vagrant"
  hosts: "{{ hosts }}"
  gather_facts: true
  roles:
    - bootstrap
